# Authorization: 
GET https://pandikk.pythonanywhere.com/api/

###

GET https://pandikk.pythonanywhere.com/api/
Authorization: token dacee1060889841bdb8ddf3c634cd97d4793b267
###

POST https://pandikk.pythonanywhere.com/api-auth-token/
Content-type: application/json;

{
    "username" : "admin",
    "password" : "admin"
}

###

POST https://pandikk.pythonanywhere.com/api/todo/
Content-type: application/json;
Authorization: token dacee1060889841bdb8ddf3c634cd97d4793b267

{
    "title": "title",
    "author": "pandik",
    "tags": ["Кухня"],
    "is_made": true
}

###

PATCH https://pandikk.pythonanywhere.com/api/todo/1/
Content-type: application/json;
Authorization: token dacee1060889841bdb8ddf3c634cd97d4793b267

{
    "is_made": true
}

###

DELETE https://pandikk.pythonanywhere.com/api/todo/3/
Authorization: token dacee1060889841bdb8ddf3c634cd97d4793b267

###
POST http://localhost:8000/api-auth-token/
Content-type: application/json;

{
    "username" : "admin",
    "password" : "admin"
}

###

DELETE https://pandikk.pythonanywhere.com/api/todo/6/
Authorization: token dacee1060889841bdb8ddf3c634cd97d4793b267
Content-type: application/json;

{

}